stages:
  data_ingestion:
    cmd: python src/ChestDiseasePrediction/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/ChestDiseasePrediction/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs: 
      - artifacts/data_ingestion/Chest-CT-Scan-data

  prepare_base_model:
    cmd: python src/ChestDiseasePrediction/pipeline/stage_02_prepare_base_model.py
    deps: 
      - src/ChestDiseasePrediction/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs: 
      - artifacts/prepare_base_model

  model_training:
    cmd: python src/ChestDiseasePrediction/pipeline/stage_03_model_training.py
    deps: 
      - src/ChestDiseasePrediction/pipeline/stage_03_model_training.py
      - config/config.yaml 
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params: 
      - IMAGE_SIZE
      - AUGMENTATION
      - BATCH_SIZE
      - EPOCHS
    outs: 
      - artifacts/model_training/model.h5

  model_evaluation:
    cmd: python src/ChestDiseasePrediction/pipeline/stage_04_model_evaluation.py
    deps: 
      - src/ChestDiseasePrediction/pipeline/stage_04_model_evaluation.py
      - config/config.yaml 
      - artifacts/model_training/model.h5
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params: 
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics: 
    - scores.json:
        cache: false

  